# Generated by Django 5.0.4 on 2024-04-27 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_Customer_model_creation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('personal-car', 'Personal Car'), ('personal-property', 'Personal Property'), ('life-coverage', 'Life Coverage'), ('accident-coverage', 'Accident Coverage')], max_length=25)),
                ('premium', models.IntegerField(default=None, null=True)),
                ('coverage', models.IntegerField(default=None, null=True)),
                ('state', models.CharField(choices=[('quoted', 'Quoted'), ('accepted', 'Accepted'), ('active', 'Active')], default='quoted', max_length=25)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_id', to='v1.customer')),
            ],
        ),
    ]
