# Generated by Django 5.0.4 on 2024-04-28 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_quote_model_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='coverage',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='quote',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='v1.customer'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='premium',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='QuoteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='v1.quote')),
            ],
        ),
    ]
