# Generated by Django 5.0.4 on 2024-04-26 13:21

from django.db import migrations
from django.contrib.auth.models import Group, User
from django.contrib.auth.hashers import make_password

def add_superuser(apps, schema_editor):
    admin_group = Group.objects.create(name='admin')
    admin_user = User.objects.create(
        username='admin',
        password=make_password('admin123'),
        is_staff=True,
        is_superuser=True
    )
    admin_user.groups.add(admin_group)



class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_superuser),
    ]
